### ISSUE TITLE
Callback URL Authentication Problemi.

### ISSUE THREAD

**Issue by scorpion86** [armutcom/iyzipay-dotnet-client#21]
Merhaba!
Sizin clientınızı kullanarak iyzico entegrasyonu yapmaya çalışıyorum. Ancak başarılı bir işlemden sonra iyzico sandbox adresinden localhost ta ki siteye dönüş yaparken bir şekilde authentice olmamış gibi login sayfasına yönleniyor. Ancak aynı sayfayı tekrar yenilediğimde bu sefer açılıyor. Buradaki sorunu çözebilmek için cors policy ekledim. Ancak faydası olmadı. Bu arada proje asp.net core 2.2 mvc. Yardımınız için şimdiden teşekkürler.

**Comment by akselarzuman** [comment]
@scorpion86 Merhaba, daha iyi yardımcı olabilmemiz adına örnek bir proje paylaşabilir misiniz?

**Comment by scorpion86** [comment]
Merhabalar.
Sorunun çözümünü buldum. Cors Policy ile pek bir ilgisi yokmuş. Belki aynı sorunla karşılaşacak olan arkadaşlar için faydalı olması maksadıyla yazıyorum.

Startup.cs dosyasının ConfigureServices metoduna aşağıdaki kodu ekleyince sorun çözüldü. 

` services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.SameSite = SameSiteMode.None;
            });`

Bildiğim kadarı ile default değer olarak SameSiteMode.Lax ayarlı olduğu için callback işlemi gerçekleştiğinde cookieler okunamıyordu. Bu nedenle sanki login olmamış gibi davranıyodu.  Yukarıdaki kodu ekleyince okunabilir hale geldi. Güvenlik açısından herhangi bir sıkıntı yaratır mı incelemedim. Daha iyi bir önerisi olan paylaşırsa sevinirim. İyi günler.

**Comment by azzopolo** [comment]
Merhabalar. Bende hala HTTP ERROR 400 veriyor

**Comment by berkayalcin** [comment]
> Merhabalar.
> Sorunun çözümünü buldum. Cors Policy ile pek bir ilgisi yokmuş. Belki aynı sorunla karşılaşacak olan arkadaşlar için faydalı olması maksadıyla yazıyorum.
> 
> Startup.cs dosyasının ConfigureServices metoduna aşağıdaki kodu ekleyince sorun çözüldü.
> 
> ` services.ConfigureApplicationCookie(options => { options.Cookie.SameSite = SameSiteMode.None; });`
> 
> Bildiğim kadarı ile default değer olarak SameSiteMode.Lax ayarlı olduğu için callback işlemi gerçekleştiğinde cookieler okunamıyordu. Bu nedenle sanki login olmamış gibi davranıyordu. Yukarıdaki kodu ekleyince okunabilir hale geldi. Güvenlik açısından herhangi bir sıkıntı yaratır mı incelemedim. Daha iyi bir önerisi olan paylaşırsa sevinirim. İyi günler.

Kardeşim Çok Sağol Hayat Kurtardın

**Comment by erdoganturkmen** [comment]
Merhabalar,

Ben de @scorpion86  gibi aynı sorunu yaşıyorum. Çözüm önerisini denedim ancak hala callBackUrl adresine düşmüyor sonuç. Login iken bir kere düşüyor, sonrasında ise tekrar düşmesi için logout oluyorum, tekrar login oluyorum. Sonra sadece bir kere callBackUrl adresine düşüyor.

Sorunu çözebilen var mı acaba ?

**Comment by gokhansegna** [comment]
Merhabalar bende de aynı sorun vardı blazor url post olarak çalıştıramadım blazora mvc controller ekleyip oradan yönlendirdim.
bu şekilde çözüm sağlamış oldum
yönledirme 
CallbackUrl = BaseAddress + "/Home?calback=false";

[ApiController]
    [Route("[controller]")]
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(bool calback = false)
        {
            return View();
        }
   }

**Comment by erdoganturkmen** [comment]
Merhabalar Gökhan bey,

Aradan bayağı zaman geçmiş ama yine de teşekkürler.

allowanonymous attribute ile çözmüştüm sorunumu.

İyi çalışmalar.

**Comment by raysefo** [comment]
Blazor Wasm için aynı sorunu yaşıyorum
